global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "bookstore"
    metrics_path: /metrics
    static_configs:
      - targets: ["bookstore:3000"]
        labels:
          service: "bookstore"
          env: "production"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
