version: "3.9"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.16.2
    container_name: mlflow-server
    ports:
      - "5000:5000"
    environment:
      MLFLOW_S3_ENDPOINT_URL: ""
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
    volumes:
      - mlflow-data:/mlflow
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - mlops-net

  trainer:
    build:
      context: .
      dockerfile: Dockerfile
    image: mlops-trainer:1.0.0
    container_name: mlflow-trainer
    depends_on:
      mlflow:
        condition: service_healthy
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    volumes:
      - mlflow-data:/mlflow
    command: python train.py --tracking-uri http://mlflow:5000
    networks:
      - mlops-net

  model-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: mlops-trainer:1.0.0
    container_name: model-api
    depends_on:
      mlflow:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MODEL_NAME: cancer-detector
      MODEL_ALIAS: champion
      USE_SCALER: "true"
    volumes:
      - mlflow-data:/mlflow
    restart: unless-stopped
    networks:
      - mlops-net

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: mlops-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=7d
    networks:
      - mlops-net

  grafana:
    image: grafana/grafana:11.1.0
    container_name: mlops-grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mlops-net

volumes:
  mlflow-data:
  prometheus-data:
  grafana-data:

networks:
  mlops-net:
    driver: bridge
